### ISSUE TITLE
error: member function declared with "override" does not override a base class member

### ISSUE THREAD

**Issue by guofenggitlearning** [Stephenfang51/YOLOP-TensorRT#1]
error: member function declared with "override" does not override a base class member,您好这个基类函数在哪里？？

**Comment by Stephenfang51** [comment]
> error: member function declared with "override" does not override a base class member,您好这个基类函数在哪里？？

编译的时候报的错? 有完整的吗

**Comment by guofenggitlearning** [comment]
tensorrt版本较高的问题，已经解决了。
tensorrt,之前是：
 8.0.1.6-1+cuda1
现在换成7.1.3.0-1+cuda1
